<?php
include('../private/db_connection_GCP.php');

// this code it's only gonna run if we click in search
// if search button is clicked

function displayArtTable() {
    global $connection;
    // this query is required to be able to show properly the arts table
    $sql_fav = "SELECT * from favourites  WHERE favourites.UserID = ".$_SESSION['loggedUserId'].";";
    // $result_fav is a row from favourites table
    $result_fav = mysqli_query($connection, $sql_fav);

    // if mysqli_query returns true (which means there is a row in favourites table with this UserID) do this
    if ($result_fav) {
        // use JS to declare array favData that's gonna be used in table.js inside the function to create buttons
        echo '<script type="text/javascript">
                var favData = []; 
            </script>';
        // while there's a row in my favourites table in the database do this
        while($row_fav = mysqli_fetch_assoc($result_fav)) {
            // using the associative array generated by the mysqli_fetch_assoc I can access the UserID index or column
            // and compares it to the loggedUserID in the SESSION if they are equal do this
            // use JS to include this favourite in the favData array, saving the the ArtID and the UserID because??
            echo '<script type="text/javascript">
                favData.push("'.$row_fav["ArtID"].'");
            </script>';
        }
    }

    // query to show the art table for customer when there's nothing entered on search
    $sql = "SELECT arts.ArtID, arts.Title, artists.FirstName, artists.LastName, arts.ArtType
    FROM arts
    INNER JOIN artists ON arts.ArtistID =  artists.ArtistID
    ORDER BY arts.ArtID;";
   
    $result = mysqli_query($connection, $sql);
    // if it exists a row in this inner join table do this
    if ($result) {
        // use JS to create artData table
        echo '<script type="text/javascript">
                var artData = []; 
            </script>';

        // output data of each row
        while($row = mysqli_fetch_assoc($result)) {
            echo '<script type="text/javascript">
                    artData.push({
                        ID: "'.$row["ArtID"].'",
                        Title: "'.$row["Title"].'",
                        Artist: "'.$row["FirstName"].' '.$row["LastName"].'",
                        Type: "'.$row["ArtType"].'",
                        Actions: ["favourite"]
                    });
                </script>';
        }

    } else {
        echo "0 results";
    }
}
?>